<?xml version="1.0"?>

<!--

Gazebo Fixedwing Definition File
Author: Gary Ellingson

-->

<robot name="fixedwing" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Properties -->
  <xacro:property name="namespace" value="fixedwing"/>
  <xacro:property name="wind_speed_topic" value="gazebo/wind_speed"/>
  <xacro:property name="use_mesh_file" value="true" />
  <xacro:property name="mesh_file" value="model://zephyr_delta_wing/meshes/wing.dae"/>
  <xacro:property name="body_width" value="1.4"/>
  <xacro:property name="body_height" value="1.0" />
  <xacro:property name="body_length" value="1.6"/>
  <xacro:property name="mass" value="1.5"/>
  <xacro:property name="Jx" value="0.1147"/>
  <xacro:property name="Jy" value="0.0576"/>
  <xacro:property name="Jz" value="0.1712"/>
  <xacro:property name="Jxz" value="0.0015"/>

  <!-- Property Blocks -->
  <xacro:property name="empty_inertia">
    <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.001" />
  </xacro:property>

  <!-- Instantiate Link and Visual -->
  <link name="${namespace}/base_link">
    <inertial>
      <mass value="${mass}" />
      <origin xyz="0 0 0" />
      <inertia ixx="${Jx}" ixy="0.00" ixz="${Jxz}" iyy="${Jy}" iyz="0.00" izz="${Jz}" />
    </inertial>
    <visual name="plane_visual">
      <origin xyz="0 0 0" rpy="0 0 1.570796" />
      <geometry>
        <xacro:if value="${use_mesh_file}">
          <mesh filename="${mesh_file}" scale="1 1 1" />
        </xacro:if>
        <xacro:unless value="${use_mesh_file}">
            <box size="${body_width} ${body_height} ${body_length}" />
        </xacro:unless>
      </geometry>
    </visual>
    <collision name="plane_collision">
      <origin xyz="0 0 0" rpy="1.570796 0 1.570796" />
      <geometry>
        <box size="${body_width} ${body_height} ${body_length}" />
      </geometry>
    </collision>

    <!-- Wheels
    <xacro:include filename="$(find fcu_sim_plugins)/xacro/wheel.xacro"/>
    <xacro:caster
      radius="0.05">
      <origin xyz="${body_length*0.5} -${body_width*0.5} -${body_height*0.5}"/>
    </xacro:caster>
    <xacro:caster
      radius="0.05">
      <origin xyz="${body_length*0.5} ${body_width*0.5} -${body_height*0.5}"/>
    </xacro:caster>
    <xacro:caster
      radius="0.05">
      <origin xyz="-${body_length*0.5} 0 -${body_height*0.4}"/>
    </xacro:caster> -->
  </link>

  <!-- ROSflight_sill -->
  <xacro:include filename="$(find rosflight_sim)/xacro/rosflight_sil.xacro"/>
  <xacro:generic_fixedwing namespace="${namespace}" parent_link="${namespace}/base_link"/>

  <!-- Chase Camera
  <xacro:include filename="$(find fcu_sim_plugins)/xacro/camera.xacro"/>
  <xacro:simple_camera
    namespace="${namespace}/chase"
    frame_rate="30"
    rgb_range="1000"
    parent_link="${namespace}/base_link"
    image_topic="rgb"
    image_camera_info_topic="camera_info">
    <origin xyz="-${1.1*body_length} 0 ${0.8*body_height}"/>
  </xacro:simple_camera> -->

  <!-- Color
  <gazebo reference="${namespace}/base_link">
    <material>Gazebo/Blue</material>
  </gazebo> -->

</robot>
